# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FILM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=50, verbose_name='电影名')),
                ('cover_img_link', models.CharField(max_length=500, null=True, verbose_name='封面图片链接')),
                ('download_link', models.CharField(max_length=500, null=True, verbose_name='下载链接')),
                ('film_intro', models.CharField(max_length=5000, null=True, verbose_name='电影剧情简介')),
                ('film_director', models.CharField(max_length=50, null=True, verbose_name='导演')),
                ('film_actors', models.CharField(max_length=500, null=True, verbose_name='演员们')),
                ('film_disc', models.CharField(max_length=5000, null=True, verbose_name='电影评论')),
                ('film_pub_year', models.CharField(max_length=50, null=True, verbose_name='电影发行年代')),
                ('dim_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-dim_date'],
                'verbose_name_plural': '电影表们',
                'verbose_name': '电影表',
            },
        ),
        migrations.CreateModel(
            name='TAG_FILM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('dim_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': '标签对照们',
                'verbose_name': '标签对照表',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='tags',
            field=models.ManyToManyField(to='core.TAG_FILM'),
        ),
    ]
