# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FILM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=50, verbose_name='电影名')),
                ('cover_img_link', models.CharField(max_length=500, null=True, verbose_name='封面图片链接')),
                ('download_link', models.CharField(max_length=500, null=True, verbose_name='下载链接')),
                ('film_html', models.CharField(max_length=50000, null=True, verbose_name='电影详情页面html')),
                ('film_disc', models.CharField(max_length=5000, null=True, verbose_name='电影评论')),
                ('dim_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '电影表们',
                'verbose_name': '电影表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TAG_FILM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('dim_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '标签对照们',
                'verbose_name': '标签对照表',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='tags',
            field=models.ManyToManyField(to='core.TAG_FILM'),
        ),
    ]
