# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_country',
            field=models.CharField(max_length=50, null=True, verbose_name='电影来自国家'),
        ),
    ]
