# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_html',
            field=models.TextField(null=True, verbose_name='电影详情页面html'),
        ),
    ]
