# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-29 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_film_film_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='download_link',
            field=models.CharField(max_length=5000, null=True, verbose_name='下载链接'),
        ),
    ]
