# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-01 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160829_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVSERIES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvseries_name', models.CharField(max_length=50, verbose_name='电视剧名')),
                ('tags', models.CharField(max_length=50, null=True, verbose_name='电视剧类型')),
                ('cover_img_link', models.CharField(max_length=500, null=True, verbose_name='封面图片链接')),
                ('download_link', models.CharField(max_length=10000, null=True, verbose_name='下载链接')),
                ('tvseries_intro', models.CharField(max_length=5000, null=True, verbose_name='电视剧情简介')),
                ('tvseries_director', models.CharField(max_length=50, null=True, verbose_name='导演')),
                ('tvseries_actors', models.CharField(max_length=500, null=True, verbose_name='演员们')),
                ('tvseries_disc', models.CharField(max_length=5000, null=True, verbose_name='电视剧评论')),
                ('tvseries_pub_year', models.CharField(max_length=50, null=True, verbose_name='电视剧发行年代')),
                ('tvseries_country', models.CharField(max_length=50, null=True, verbose_name='电视剧来自国家')),
                ('dim_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': '电视剧表',
                'ordering': ['-dim_date'],
                'verbose_name_plural': '电视剧表们',
            },
        ),
    ]
