# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170209_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACTORS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='演员名字')),
                ('douban_id', models.CharField(max_length=100, null=True, verbose_name='演员豆瓣id')),
                ('alt', models.CharField(max_length=200, null=True, verbose_name='豆瓣链接')),
                ('small_douban_image', models.CharField(max_length=200, null=True, verbose_name='豆瓣演员小海报图')),
                ('middle_douban_image', models.CharField(max_length=200, null=True, verbose_name='豆瓣演员中海报图')),
                ('big_douban_image', models.CharField(max_length=200, null=True, verbose_name='豆瓣演员大海报图')),
                ('dim_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-dim_date'],
                'verbose_name_plural': '演员们',
                'verbose_name': '演员',
            },
        ),
        migrations.CreateModel(
            name='DIRECTORS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='导演名字')),
                ('douban_id', models.CharField(max_length=100, null=True, verbose_name='导演豆瓣id')),
                ('alt', models.CharField(max_length=200, null=True, verbose_name='豆瓣链接')),
                ('small_douban_image', models.CharField(max_length=200, null=True, verbose_name='豆瓣导演小海报图')),
                ('middle_douban_image', models.CharField(max_length=200, null=True, verbose_name='豆瓣导演中海报图')),
                ('big_douban_image', models.CharField(max_length=200, null=True, verbose_name='豆瓣导演大海报图')),
                ('dim_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-dim_date'],
                'verbose_name_plural': '导演们',
                'verbose_name': '导演',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='alt',
            field=models.CharField(max_length=100, null=True, verbose_name='豆瓣电影地址'),
        ),
        migrations.AddField(
            model_name='film',
            name='big_douban_image',
            field=models.CharField(max_length=200, null=True, verbose_name='豆瓣电影大海报图'),
        ),
        migrations.AddField(
            model_name='film',
            name='collect_count',
            field=models.CharField(max_length=50, null=True, verbose_name='看过人数'),
        ),
        migrations.AddField(
            model_name='film',
            name='comments_count',
            field=models.CharField(max_length=50, null=True, verbose_name='短评人数'),
        ),
        migrations.AddField(
            model_name='film',
            name='douban_id',
            field=models.CharField(max_length=50, null=True, verbose_name='豆瓣id'),
        ),
        migrations.AddField(
            model_name='film',
            name='douban_title',
            field=models.CharField(max_length=100, null=True, verbose_name='豆瓣电影名称'),
        ),
        migrations.AddField(
            model_name='film',
            name='middle_douban_image',
            field=models.CharField(max_length=200, null=True, verbose_name='豆瓣电影中海报图'),
        ),
        migrations.AddField(
            model_name='film',
            name='origin_title',
            field=models.CharField(max_length=100, null=True, verbose_name='原名'),
        ),
        migrations.AddField(
            model_name='film',
            name='ratings_count',
            field=models.CharField(max_length=50, null=True, verbose_name='评分人数'),
        ),
        migrations.AddField(
            model_name='film',
            name='reviews_count',
            field=models.CharField(max_length=50, null=True, verbose_name='影评人数'),
        ),
        migrations.AddField(
            model_name='film',
            name='small_douban_image',
            field=models.CharField(max_length=200, null=True, verbose_name='豆瓣电影小海报图'),
        ),
        migrations.AddField(
            model_name='film',
            name='stars',
            field=models.CharField(max_length=50, null=True, verbose_name='电影评分'),
        ),
        migrations.AddField(
            model_name='film',
            name='wish_count',
            field=models.CharField(max_length=50, null=True, verbose_name='想看的人数'),
        ),
        migrations.AlterField(
            model_name='film',
            name='download_link2',
            field=models.CharField(max_length=500, null=True, verbose_name='下载链接2'),
        ),
        migrations.AlterField(
            model_name='film',
            name='download_link3',
            field=models.CharField(max_length=500, null=True, verbose_name='下载链接3'),
        ),
    ]
