# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170213_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(to='core.ACTORS'),
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(to='core.DIRECTORS'),
        ),
    ]
