# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170213_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='if_useapi',
            field=models.CharField(max_length=50, null=True, verbose_name='是否调用过api'),
        ),
    ]
