# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170224_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='AKA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='别名')),
                ('dim_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '别名表们',
                'verbose_name': '别名表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='国家')),
            ],
            options={
                'verbose_name_plural': '国家表们',
                'verbose_name': '国家表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Film_genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '标签对照们',
                'verbose_name': '标签对照表',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='subtype',
            field=models.CharField(max_length=200, null=True, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='film',
            name='aka',
            field=models.ManyToManyField(to='core.AKA'),
        ),
        migrations.AddField(
            model_name='film',
            name='douban_country',
            field=models.ManyToManyField(to='core.Countries'),
        ),
        migrations.AddField(
            model_name='film',
            name='douban_genres',
            field=models.ManyToManyField(to='core.Film_genres'),
        ),
    ]
